#!/bin/bash
#PBS -A lp_edu_evol_quant_genetics
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=8

cd $VSC_SCRATCH/CompAss
module purge
module load BLAST+

makeblastdb -in GloeobacterViolaceus.faa -dbtype prot -parse_seqids -out GV
makeblastdb -in TheobromaCacao.faa -dbtype prot -parse_seqids -out TC
blastp -query GloeobacterViolaceus.faa -db TC -outfmt 6 -out GVqTCd_a.out -num_threads 8
blastp -query TheobromaCacao.faa -db GV -outfmt 6 -out TCqGVd_a.out -num_threads 8
blastp -query GloeobacterViolaceus.faa -db GV -outfmt 6 -out GVqGVd_a.out -num_threads 8
blastp -query TheobromaCacao.faa -db TC -outfmt 6 -out TCqTCd_a.out -num_threads 8
